import { useState } from "react";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useLanguage } from "@/lib/i18n";

const Application = () => {
    const { t } = useLanguage();
    const [step, setStep] = useState(1);
    const [formData, setFormData] = useState<any>({});
    const [isRejected, setIsRejected] = useState(false);

    // Dynamic Options from i18n
    // Dynamic Options from i18n
    const SPEND_OPTS = t.app.spend.opts.map((opt, idx) => ({
        ...opt,
        // Logic mapping: keep original values for logic if needed, or just map by index/id in real app
        // Here we map back to the logical values 
        reject: false // Logic: Allow all stages including growth
    }));

    const PAIN_OPTS = t.app.pain.opts;
    const IT_OPTS = t.app.it.opts;

    const handleSpendSelect = (opt: any) => {
        setFormData({ ...formData, spend: opt.value });
        // Logic: All applicants proceed to next step
        setStep(2);
    };

    const handlePainSelect = (opt: any) => {
        setFormData({ ...formData, pain: opt.value });
        setStep(3);
    };

    const handleITSelect = (opt: any) => {
        setFormData({ ...formData, it: opt.value });
        setStep(4);
    };

    const handleContextSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setStep(5);
    };

    const handleFinalSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Helper to safe string
        const safe = (str: any) => str || "N/A";
        const getOptLabel = (opts: any[], val: any) => opts.find(o => o.value === val)?.label || val;

        const subject = "SIGNAL TRANSMISSION: Operational Clearance Request";
        const body = `
SIGNAL TRANSMISSION DATA
------------------------

CALIBRATION (Scale): ${safe(getOptLabel(SPEND_OPTS, formData.spend))}
DIAGNOSTIC (Vector): ${safe(getOptLabel(PAIN_OPTS, formData.pain))}
TERRAIN (IT): ${safe(getOptLabel(IT_OPTS, formData.it))}

INTEL (Context):
${safe(formData.context)}

IDENTITY
--------
Name: ${safe(formData.name)}
Organization: ${safe(formData.company)}
Email: ${safe(formData.email)}
Role: ${safe(formData.role)}

------------------------
Generated by TorqueFoundry Application
        `.trim();

        const payload = {
            to: "info@torquefoundryadvisory.com",
            replyTo: formData.email,
            subject: subject,
            text: body
        };

        toast.info("TRANSMITTING SIGNAL...");

        try {
            const response = await fetch('http://localhost:3001/api/send-email', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(payload),
            });

            const data = await response.json();

            if (data.success) {
                toast.success("SIGNAL TRANSMITTED SUCCESSFULLY.");
                setTimeout(() => {
                    window.location.href = "/";
                }, 2000);
            } else {
                toast.error("TRANSMISSION FAILED. PLEASE TRY AGAIN OR EMAIL DIRECTLY.");
                console.error("Transmission Error:", data);
            }
        } catch (error) {
            toast.error("CONNECTION ERROR. SYSTEM OFFLINE.");
            console.error("Detailed Error:", error);
        }
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    // Helper to find label by value for summary
    const getLabel = (opts: { label: string, value: string }[], val: string) => opts.find(o => o.value === val)?.label;

    return (
        <div className="relative z-10 min-h-screen bg-background text-foreground font-mono">
            <SiteHeader />
            <main className="mx-auto max-w-2xl px-4 py-24">
                <div className="mb-12 border-l-4 border-primary pl-6">
                    <h1 className="font-display text-4xl uppercase tracking-tighter text-foreground mb-2">
                        {t.nav.signal_check_btn}
                    </h1>
                    <p className="text-sm text-muted-foreground uppercase tracking-widest">
                        CO-INVESTMENT DIAGNOSTIC APPLICATION
                    </p>
                </div>

                {isRejected ? (
                    <div className="border border-border bg-secondary/20 p-8 rounded-lg">
                        <h2 className="text-xl text-primary mb-4 font-bold">{t.app.rejection.status}</h2>
                        <p className="text-muted-foreground">
                            {t.app.rejection.msg}
                        </p>
                        <Button className="mt-6" variant="outline" onClick={() => window.location.href = "/"}>
                            {t.app.rejection.btn}
                        </Button>
                    </div>
                ) : (
                    <div className="space-y-8">
                        {step === 1 && (
                            <div className="animate-in fade-in slide-in-from-bottom-4">
                                <h3 className="text-lg text-accent mb-6 uppercase tracking-widest">{t.app.steps.calibration}</h3>
                                <p className="mb-6 text-xl">{t.app.spend.question}</p>
                                <div className="space-y-3">
                                    {SPEND_OPTS.map((opt) => (
                                        <button
                                            key={opt.value}
                                            onClick={() => handleSpendSelect(opt)}
                                            className="w-full text-left p-4 border border-border hover:border-primary hover:bg-secondary/40 transition-all uppercase tracking-wider text-sm"
                                        >
                                            [ ] {opt.label}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        )}

                        {step === 2 && (
                            <div className="animate-in fade-in slide-in-from-bottom-4">
                                <h3 className="text-lg text-accent mb-6 uppercase tracking-widest">{t.app.steps.diagnostics}</h3>
                                <p className="mb-6 text-xl">{t.app.pain.question}</p>
                                <div className="space-y-3">
                                    {PAIN_OPTS.map((opt) => (
                                        <button
                                            key={opt.value}
                                            onClick={() => handlePainSelect(opt)}
                                            className="w-full text-left p-4 border border-border hover:border-primary hover:bg-secondary/40 transition-all uppercase tracking-wider text-sm"
                                        >
                                            [ ] {opt.label}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        )}

                        {step === 3 && (
                            <div className="animate-in fade-in slide-in-from-bottom-4">
                                <h3 className="text-lg text-accent mb-6 uppercase tracking-widest">{t.app.steps.terrain}</h3>
                                <p className="mb-6 text-xl">{t.app.it.question}</p>
                                <div className="space-y-3">
                                    {IT_OPTS.map((opt) => (
                                        <button
                                            key={opt.value}
                                            onClick={() => handleITSelect(opt)}
                                            className="w-full text-left p-4 border border-border hover:border-primary hover:bg-secondary/40 transition-all uppercase tracking-wider text-sm"
                                        >
                                            [ ] {opt.label}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        )}

                        {step === 4 && (
                            <div className="animate-in fade-in slide-in-from-bottom-4">
                                <h3 className="text-lg text-accent mb-6 uppercase tracking-widest">{t.app.steps.intel}</h3>
                                <p className="mb-6 text-xl">{t.app.context.title}</p>
                                <p className="mb-4 text-sm text-muted-foreground">{t.app.context.desc}</p>
                                <form onSubmit={handleContextSubmit} className="space-y-6">
                                    <textarea
                                        name="context"
                                        rows={6}
                                        className="w-full bg-secondary/10 border border-border p-4 text-sm focus:border-accent focus:ring-1 focus:ring-accent outline-none rounded-sm resize-none"
                                        placeholder={t.app.context.placeholder}
                                        onChange={handleInputChange}
                                    />
                                    <Button
                                        size="lg"
                                        className="w-full bg-primary hover:bg-primary/90 text-white font-bold tracking-[0.2em] uppercase"
                                        type="submit"
                                    >
                                        {t.app.context.btn}
                                    </Button>
                                </form>
                            </div>
                        )}

                        {step === 5 && (
                            <div className="animate-in fade-in slide-in-from-bottom-4">
                                <h3 className="text-lg text-accent mb-6 uppercase tracking-widest">{t.app.steps.identity}</h3>
                                <div className="bg-secondary/10 p-6 border border-border mb-8 space-y-2 text-xs">
                                    <p><span className="text-muted-foreground mr-4">{t.app.identity.summary_labels.calibration}:</span> {getLabel(SPEND_OPTS, formData.spend)?.toUpperCase()}</p>
                                    <p><span className="text-muted-foreground mr-4">{t.app.identity.summary_labels.diagnostic}:</span> {getLabel(PAIN_OPTS, formData.pain)?.toUpperCase()}</p>
                                    <p><span className="text-muted-foreground mr-4">{t.app.identity.summary_labels.terrain}:</span> {getLabel(IT_OPTS, formData.it)?.toUpperCase()}</p>
                                </div>

                                <form onSubmit={handleFinalSubmit} className="space-y-4">
                                    <div className="grid gap-4 md:grid-cols-2">
                                        <div className="space-y-2">
                                            <label className="text-xs uppercase tracking-widest text-muted-foreground">{t.app.identity.labels.name}</label>
                                            <input
                                                required
                                                name="name"
                                                type="text"
                                                className="w-full h-12 px-4 bg-background border border-border focus:border-accent outline-none"
                                                placeholder={t.app.identity.placeholders.name}
                                                onChange={handleInputChange}
                                            />
                                        </div>
                                        <div className="space-y-2">
                                            <label className="text-xs uppercase tracking-widest text-muted-foreground">{t.app.identity.labels.org}</label>
                                            <input
                                                required
                                                name="company"
                                                type="text"
                                                className="w-full h-12 px-4 bg-background border border-border focus:border-accent outline-none"
                                                placeholder={t.app.identity.placeholders.org}
                                                onChange={handleInputChange}
                                            />
                                        </div>
                                    </div>

                                    <div className="space-y-2">
                                        <label className="text-xs uppercase tracking-widest text-muted-foreground">{t.app.identity.labels.email}</label>
                                        <input
                                            required
                                            name="email"
                                            type="email"
                                            className="w-full h-12 px-4 bg-background border border-border focus:border-accent outline-none"
                                            placeholder={t.app.identity.placeholders.email}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <div className="space-y-2">
                                        <label className="text-xs uppercase tracking-widest text-muted-foreground">{t.app.identity.labels.role}</label>
                                        <input
                                            name="role"
                                            type="text"
                                            className="w-full h-12 px-4 bg-background border border-border focus:border-accent outline-none"
                                            placeholder={t.app.identity.placeholders.role}
                                            onChange={handleInputChange}
                                        />
                                    </div>

                                    <Button
                                        size="lg"
                                        className="w-full mt-6 bg-accent hover:bg-accent/90 text-accent-foreground font-bold tracking-[0.2em] uppercase py-6 shadow-[0_0_20px_hsl(var(--accent)_/_0.4)]"
                                        type="submit"
                                    >
                                        {t.app.identity.btn}
                                    </Button>
                                    <p className="text-[0.6rem] text-center text-muted-foreground pt-4">
                                        {t.app.identity.disclaimer}
                                    </p>
                                </form>
                            </div>
                        )}
                    </div>
                )}
            </main>
            <SiteFooter />
        </div>
    );
};

export default Application;
